### ISSUE TITLE
ipa -> apple store connect ?

### ISSUE THREAD

**Issue by flutter-painter** [damienaicheh/demo_flutter_github_actions#2]
Thank you @damienaicheh for this repo and detailed tuto.
Regarding ios signing and publishing to apple store connect,
It does not seem so simple to send the .ipa to the apple store connect for publishing in prod.

I wonder if using [appcenter](https://learn.microsoft.com/en-us/appcenter/distribution/stores/apple) or codemagic is not more adequate since they also provide this last step.

I am curious to read your thought on the topic, 
if you prefer to exchange elsewhere or via pm instead of issues I will gladly follow

Best

**Comment by damienaicheh** [comment]
Hello,

You can close the issue and contact me on LinkedIn it will be easier.

Damien

**Comment by flutter-painter** [comment]
Hi Damien,
Yes sorry for the delay,
Turned out that for deploying iOS app Codemagic turned out simple as magic,
I gather however that using github action can serve other CICD purposes,
Thanks again for sharing this resource for Flutter

**Comment by damienaicheh** [comment]
Hi, ok good news! Happy coding!
